export * from './header/header';
export * from './footer/footer';
export * from './icon/icon';
export * from './input/input'
export * from './button/button'
export * from './h2/h2';
export * from './auth-form-error/auth-form-error'
export * from './styled-link-form/styled-link-form'
export * from './private-content/private-content'
export * from './modal/modal'
export * from './error/error'